# use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.
# Listener configuration
case-listener:
   http-client:
      client-id: "![DaPFpmc6y6I=]"
      client-secret: "![sgi/h//FjVg=]"
anypoint-mq:
  client-id:  "![JuDVixvFQkt0MfPH6HQbRHLPI8y7LS0sq6mUXI3pLwTAs9jDNXEhEA==]"
  client-secret: "![29vLdcoaAXrXsjGA/9nFrqv4npXI8qLg5T0nu6++ibS0zDxLVEjj9A==]"
      
            
